version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: lilcassandra
    environment:
      - "CASSANDRA_CLUSTER_NAME=my-cassandra-cluster"
    ports:
      - "9042:9042"
    expose:
      - "9042"
      - "7000"
      - "7001"
      - "9160"
    volumes:
      - ./data:/var/lib/cassandra
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
      - ./db/scripts/create-keyspace.cql:/docker-entrypoint-initdb.d/db/scripts/create-keyspace.cql
      - ./db/scripts/schema.cql:/docker-entrypoint-initdb.d/db/scripts/schema.cql
    restart: unless-stopped

  server:
    depends_on:
      - cassandra
    container_name: lilapi-server
    environment:
      - "TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}"
    ports:
      - "8080:8080"
    command:
      -address=":8080"
    build:
      context: .
    restart: unless-stopped
