version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra-container
    environment:
      - "CASSANDRA_CLUSTER_NAME=my-cassandra-cluster"
    ports:
      - "9042:9042"
    volumes:
      - ./data:/var/lib/cassandra
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
      - ./db/scripts/create-keyspace.cql:/docker-entrypoint-initdb.d/db/scripts/create-keyspace.cql
      - ./db/scripts/schema.sql:/docker-entrypoint-initdb.d/db/scripts/schema.sql
    restart: always