version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: lilpostgres
    environment:
      POSTGRES_USER: lil
      POSTGRES_PASSWORD: lil
      POSTGRES_DB: lil
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./db/init-scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  server:
    depends_on:
      - postgres
    container_name: lilapi-server
    environment:
      - "TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}"
      - "POSTGRESQL_URL=${POSTGRESQL_URL}"
    ports:
      - "8080:8080"
    command:
      -address=":8080"
    build:
      context: .
    restart: unless-stopped

volumes:
  database_data:
    driver: local